module.exports = {
    START_LOADING: 'START_LOADING',
    END_LOADING: 'START_LOADING',
    FETCH_ALL: 'START_LOADING',
    FETCH_PUB: 'START_LOADING',
    FETCH_PUB_BY_SEARCH: 'START_LOADING',
    DELETE: 'DELETE',
    CREATE: 'CREATE',
    UPDATE: 'UPDATE'
}
